<?xml version="1.0"?>
<!-- https://docs.nav2.org/setup_guides/urdf/setup_urdf.html#writing-the-urdf -->
<robot name="rutler" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="0.415 0.18 0.08"/>
            </geometry>
            <material name="whatever">
                <color rgba="0.8 0.7 0.8 1" />
            </material>
        </visual>
    </link>

    <link name="origo"/>
    <joint name="base_joint" type="fixed">
        <child link="base_link"/>
        <parent link="origo"/>
        <origin xyz="0.0 0.0 ${wheel_radius*2}" rpy="0 0 0"/>
    </joint>

    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
        </link>
        <!--joint name="${prefix}_joint" type="continuous"-->
        <joint name="${prefix}_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_link"/>
            <origin xyz="${x_reflect*0.26/2} ${y_reflect*0.17/2} -0.05" rpy="0 0 0"/>
            <!--axis xyz="0 1 0"/-->
        </joint>
    </xacro:macro>

    <xacro:wheel prefix="whl_fr" x_reflect="1" y_reflect="-1" />
    <xacro:wheel prefix="whl_fl" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="whl_br" x_reflect="-1" y_reflect="-1" />
    <xacro:wheel prefix="whl_bl" x_reflect="-1" y_reflect="1" />

    <link name="laser">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.03" length="0.04"/>
            </geometry>
            <material name="black">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
    </link>
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="-0.10 0.0 0.06" rpy="0 0 0"/>
    </joint>

</robot>
